<?php
session_start();
if(($_SESSION["loggedin"] != true) || ($_SESSION["is_admin"] != true)){
  header("Location: index.php");
  exit;
}

//Import PHPMailer classes into the global namespace
//These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';


$name = $_POST['username'];
$email = $_POST['email'];
$phone = $_POST['phone'];
$text = $_POST['text'];


//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer();
$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = '4bd42e0e592b72'; //paste one generated by Mailtrap
$mail->Password = 'ac9d81d045587e'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;
$mail->setFrom($email, 'Mailtrap');
$mail->addReplyTo($email, 'Mailtrap');
$mail->addAddress('daluncar@mailtrap.io', 'Tim');
$mail->Subject = 'Kontakt DalunCAR';
$mail->isHTML(true);
$mailContent = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" lang="en">
<head><link rel="stylesheet" type="text/css" hs-webfonts="true" href="https://fonts.googleapis.com/css?family=Lato|Lato:i,b,bi">
  <title>Email template</title>
  <meta property="og:title" content="Email template">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style type="text/css">
 
    a{ 
      text-decoration: underline;
      color: inherit;
      font-weight: bold;
      color: #253342;
    }
    
    h1 {
      font-size: 56px;
    }
    
      h2{
      font-size: 28px;
      font-weight: 900; 
    }
    
    p {
      font-weight: 100;
    }
    
    td {
  vertical-align: top;
    }
    
    #email {
      margin: auto;
      width: 600px;
      background-color: white;
    }
    
    button{
      font: inherit;
      background-color: #FF7A59;
      border: none;
      padding: 10px;
      text-transform: uppercase;
      letter-spacing: 2px;
      font-weight: 900; 
      color: white;
      border-radius: 5px; 
      box-shadow: 3px 3px #d94c53;
    }
    
    .subtle-link {
      font-size: 9px; 
      text-transform:uppercase; 
      letter-spacing: 1px;
      color: #CBD6E2;
    }
  </style>
</head>
  <body bgcolor="#F5F8FA" style="width: 100%; margin: auto 0; padding:0; font-family:Lato, sans-serif; font-size:18px; color:#33475B; word-break:break-word">
<div id="email">
    <table align="right" role="presentation">
      <tr>
        <td>
        <a class="subtle-link" href="#">View in Browser</a>
        </td>
        <tr>
    </table>
       <table role="presentation" width="100%">
          <tr>
       
            <td bgcolor="#00A4BD" align="center" style="color: white;">
          
           <img alt="Flower" src="https://hs-8886753.f.hubspotemail.net/hs/hsstatic/TemplateAssets/static-1.60/img/hs_default_template_images/email_dnd_template_images/ThankYou-Flower.png" width="400px" align="middle">
              
              <h1> Witaj! </h1>
              
            </td>
      </table>
<table role="presentation" border="0" cellpadding="0" cellspacing="10px" style="padding: 30px 30px 30px 60px;">
    <tr>
    <td>
      <h2>DalunCAR</h2>
          <p>Imie i nazwisko: '. $name .'</p>
          <p>Numer Telefonu: '. $phone .'</p>
          <p>Tresc wiadomosci: '. $text .'</p>
    </td> 
    </tr>
</table>
<table role="presentation" bgcolor="#EAF0F6" width="100%" style="margin-top: 50px;" >
    <tr>
        <td align="center" style="padding: 30px 30px;">
          
       <h2> DalunCAR </h2>
          <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci neque earum nam quas et ipsa similique commodi architecto magnam quidem, mollitia quo quos nemo itaque exercitationem laboriosam iusto quibusdam magni.
            </p>
            <a href="localhost/oop"> Odwiedz nas!</a>      
        </td>
        </tr>
    </table>
    </div>
  </body>
    </html>';
$mail->Body = $mailContent;
if($mail->send()){
    header("Location: index.php");
    $_SESSION["mail"] = true;
    exit();
}else{
    echo 'Wiadomosc nie zostala wyslana!';
    $_SESSION["mail"] = false;
}